### ISSUE TITLE
Move coins.conf to a folder named conf

### ISSUE THREAD

**Issue by ackr-8** [jakedolan443/cryptohttp#1]
Hey as I said that I would be building a docker container for cryptohttp, I'm having trouble with mounting coins.conf so can you please make a directory named conf or config or something like that and move coins.conf to it and do the necessary changes in the server.py file.

**Comment by jakedolan443** [comment]
Hi, I am unfamiliar with docker, please describe in detail how configuration files for cryptohttp should be setup for docker containers (possibly show me a sample directory setup). 
I have planned to create a single configuration file, named `cryptohttp.conf`, with all configuration arguments within - this will appear soon in future. Would a directory be necessary?

**Comment by ackr-8** [comment]
Ya it would be much easier if the conf file is in a directory say config/. Then we can easily mount the directory as a Volume in docker.

**Comment by jakedolan443** [comment]
Implemented in new release, v1.1
